### ISSUE TITLE
Add name to different value

### ISSUE THREAD

**Issue by mfmy20** [Dealman/Frankensteiner#1]
I have tested all value of the character face modification and i have been able to label most of them as what they do.

Unfortunately, you haven't allow upload (maybe create a new branch for this).

So if you would care to update the following file.
[file_to_update.zip](https://github.com/Dealman/Frankensteiner/files/4016205/file_to_update.zip)

**Comment by Danziir** [comment]
> 
> 
> I have tested all value of the character face modification and i have been able to label most of them as what they do.
> 
> Unfortunately, you haven't allow upload (maybe create a new branch for this).
> 
> So if you would care to update the following file.
> [file_to_update.zip](https://github.com/Dealman/Frankensteiner/files/4016205/file_to_update.zip)

Hey, just wanted to say thanks because that's exactly what I was looking for!

**Comment by H8DCarnifeX** [comment]
Sadly the Tool isnt updated yet with the names, is it already dead?

what program do i need to compile it, with the new file? (beginner here)

**Comment by mfmy20** [comment]
Sadly, yes.

And if you want to  compile it, you should propably use VisualStudio (if you take the microsoft version you should be able to compile it without anything else but google it to be sure).

**Comment by H8DCarnifeX** [comment]
Ok, thank you.

**Comment by Dealman** [comment]
Wow, this one completely escaped me. Sorry guys!

Really appreciate the effort you've put into this @mfmy20, I've gone ahead and commited the values you've found. I tried to rename the things a bit for clarity, hopefully they're still somewhat accurate.

Just lost more or less all of my interest in Mordhau, sadly. So this repository kind of went under the radar for a while. So no, it's not really dead per se - I'll still gladly update it with things like these!

@H8DCarnifeX 

Not sure if you figured it out, but this was made with Visual Studio 2019. The community version is free and you should be able to use that.

Then all you should _(more or less)_ have to do is download the project as a ZIP and unpackage it.

You'd also need .NET Framework 4.5. :)
