### ISSUE TITLE
Horde Mercenary

### ISSUE THREAD

**Issue by Dealman** [Dealman/Frankensteiner#10]
Has there been any changes to the config? Got a report that the program fails to start because Horde Mercenary returns 0 values, when 147 were expected.

I know Battle Royale was removed, and Horde mode has been overhauled - not sure if that may have something to do with it?

**Comment by Halen84** [comment]
It load up just fine for me.

I don't think I've changed anything related to horde mercenaries, so the person might have accidentally changed something. Check if the person is using the latest version maybe?

**Comment by Dealman** [comment]
Hmm, I asked them to make a backup of their current config and then remove it so it generates a new. But apparently same error.

Maybe it's an issue with permissions? I'll ask them. :)

**Comment by Halen84** [comment]
I just did the same, still no error on my end. Not sure what's wrong then

**Comment by Dealman** [comment]
Closing this, I asked them if they could provide me with their config file to look for any discrepancies. But haven't heard back from them, so for now I'll assume this is solved and working as intended.

Thanks for looking into it, Halen. 😄

**Comment by beefis** [comment]
Getting this error as of 2 patches ago. Happy to send you config in private. Worked before arid update.

**Comment by Dealman** [comment]
I don't currently have Mordhau installed to test, but you sending the config should suffice to see what's going on I believe.

**Comment by beefis** [comment]
Will do
There any way i can send this or my discord tag to you privately through github?

**Comment by Dealman** [comment]
`Dealman#3056` on Discord, I'm about to scoot off to bed but I'll look at it later. 😄

**Comment by beefis** [comment]
No worries, look for a friend request from maldhau

**Comment by Halen84** [comment]
I'll look into this later tomorrow. The newest patch(es) have definitely changed some things.

**Comment by Dealman** [comment]
The issue seems pretty easy to solve, the config now has more entries - something I assume to do with localization.

For example;
```ini
CharacterProfiles=(Name=LOCGEN_FORMAT_NAMED(NSLOCTEXT("", "CED1585D42CF639582B345B94A05EBDD", "{LoadoutName} copy"), "LoadoutName", INVTEXT("efsfesf")),GearCustomization=(Wearables=((ID=12,Colors=(20,0)),(ID=12,Colors=(17,0)),(ID=53),(ID=22,Colors=(1,0)),(ID=36,Colors=(1,0)),(ID=22,Colors=(1,0)),(ID=6,Colors=(6,6)),(ID=31,Colors=(1,0)),(ID=13,Colors=(6,6))),Equipment=((ID=6,Colors=(0,16,0),Skin=1),(ID=56,Colors=(23,16,0),Parts=(2,1,0),Skin=4),())),AppearanceCustomization=(Emblem=0,EmblemColors=(0,0),MetalRoughnessScale=0,MetalTint=16,Age=0,Voice=1,VoicePitch=255,bIsFemale=True,Fat=0,Skinny=0,Strong=255,SkinColor=0,Face=0,EyeColor=0,HairColor=0,Hair=12,FacialHair=0,Eyebrows=0),FaceCustomization=(Translate=(0,65535,0,0,65535,65535,0,0,0,0,65535,65535,65535,65535,65535,65535,0,65535,65535,65535,0,0,0,0,65535,65535,0,0,0,65535,65535,65535,65535,65535,65535,65535,0,65535,0,65535,65535,0,65535,65535,65535,0,0,65535,0),Rotate=(65535,0,65535,0,0,0,65535,65535,0,0,0,0,65535,0,0,0,0,65535,65535,0,0,0,65535,65535,65535,65535,0,65535,0,0,65535,0,0,65535,0,65535,0,65535,0,0,65535,0,0,0,65535,0,0,0,65535),Scale=(0,0,0,65535,0,65535,65535,0,65535,65535,65535,65535,0,0,65535,65535,65535,65535,0,0,65535,0,65535,65535,0,0,65535,65535,65535,0,0,65535,65535,65535,0,0,0,65535,0,0,65535,0,65535,0,65535,65535,65535,0,0)),SkillsCustomization=(Perks=2097156),Category="actual classes")
```

Since the regex is unable to parse the name in these cases, it thought it was a horde character which handles parsing a little bit differently.

https://github.com/Dealman/Frankensteiner/blob/8e2f3c72b72850ef1ea35779386c27c225929fd5/Frankensteiner/ConfigParser.cs#L59

Simply adding this to the top of the `foreach` loop in the above method should fix the issue;
```CS
if (parsedMercenary.Contains("LOCGEN") || parsedMercenary.Contains("NSLOCTEXT"))
    continue;
```

I can't quite recall how the config is saved, do we overwrite it from scratch or update values using regex? If the former, we _probably_ have to make sure these entries are added back as well so we don't break things? 🤔

**Comment by Dealman** [comment]
@beefis Sorry for the delay, this should be resolved with the latest [version 1.4.1.0](https://github.com/Dealman/Frankensteiner/releases/tag/1.4.1.0).

If you'd be so kind and download the new version and make sure it works, that would be greatly appreciated! 👍

**Comment by Halen84** [comment]
Oh sorry. I got busy and didn't get around to fixing this

**Comment by beefis** [comment]
@Dealman  Will do, will report if i have any issues

**Comment by Dealman** [comment]
I'll close this for now, assuming the issue is fixed. Feel free to re-open it if it's still not working or a new update breaks the changes. 😄
