### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Frassesburgare** [Dealman/Frankensteiner#11]
Frankenstein deleted all my mercenaries. 3 years of characters worth might I add!
Frankensteiner has worked every other time I’ve used it. I do believe the cause it because of the recent update where they added the character categories.

**Comment by Frassesburgare** [comment]
Found the mordhau Game_Backup.ini and it fixed the problem!

**Comment by Halen84** [comment]
Nice. Btw, Frankensteiner should never erase all of your loadouts. This is an issue with Mordhau itself and the devs' poor reading/writing implementation of the file.
