### ISSUE TITLE
Bones names [intel inside]

### ISSUE THREAD

**Issue by ExtReMLapin** [Dealman/Frankensteiner#4]
I managed to find some of the bones names using this script https://gist.github.com/ExtReMLapin/4f5bd8ba3aaa9fdfc2d83f076b886c3a

The idea is very simple : add this mercenary : 

`CharacterProfiles=(Name=INVTEXT("TESTBONECHAR"),GearCustomization=(Wearables=((),(),(ID=30),(),(),(),(),(ID=15),(ID=8)),Equipment=((),(),())),AppearanceCustomization=(Emblem=0,EmblemColors=(0,0),MetalRoughnessScale=0,MetalTint=0,Age=0,Voice=0,VoicePitch=127,bIsFemale=False,Fat=85,Skinny=85,Strong=85,SkinColor=0,Face=0,EyeColor=0,HairColor=0,Hair=0,FacialHair=0,Eyebrows=0),FaceCustomization=(Translate=(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),Rotate=(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),Scale=(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)),SkillsCustomization=(Perks=0))`

Go in game, move one part of the face, run script and it will output something like that : 

```txt
BONE_UNKNOWN_16 :
	translate : 928
	rotate : 0
	scale: 0
```

So you know exactly which bone you moved, then I used to change the bone names from `BONE_UNKNOWN_16 ` to `BONE_OUTTER_JAW` in the code.

I moved all the bones I could move and managed to get this list  : 

```txt
BONE_LIP_INNER
BONE_LIP_INNER_EXT
BONE_MAXILIA
BONE_WHOLE_EYEBROW_1
BONE_UNKNOWN_05
BONE_WHOLE_EYEBROW_2
BONE_EYE_1
BONE_UNKNOWN_08
BONE_UNKNOWN_09
BONE_UNKNOWN_10
BONE_WHOLE_MOUTH
BONE_EYE_2
BONE_MOUTH_COMMISSURE_1
BONE_MOUTH_COMMISSURE_2
BONE_CHIN
BONE_OUTTER_JAW
BONE_CHEEK_1
BONE_LOWERLIP_MIDDLE
BONE_LOWERLIP_1
BONE_LOWERLIP_2
BONE_UPPER_ZYGOMATIC_1
BONE_UPPERLIP_MIDDLE
BONE_UPPERLIP_1
BONE_UPPERLIP_2
BONE_PHILTRUM
BONE_NOSE_TIP
BONE_NOSE_BRIDGE
BONE_GLABELLA
BONE_UPPER_ZYGOMATIC_2
BONE_LOWER_ZYGOMATIC
BONE_CHEEK_2
BONE_EYEBROWS_1_INNER
BONE_EYEBROWS_2_INNER
BONE_EYEBROWS_1_CENTER
BONE_EYEBROWS_2_CENTER
BONE_EYEBROWS_1_EXTERIOR
BONE_EYEBROWS_2_EXTERIOR
BONE_EAR1
BONE_EAR2
BONE_UNKNOWN_40
BONE_UNKNOWN_41
BONE_EYE_1_UPPERLID
BONE_EYE_1_LOWERLID
BONE_UNKNOWN_44
BONE_UNKNOWN_45
BONE_EYE_2_UPPERLID
BONE_EYE_2_LOWERLID
BONE_ZYGOMATIC
BONE_UNKNOWN_49
```

**Comment by ExtReMLapin** [comment]
I use 1 and 2, not left or right

**Comment by Dealman** [comment]
Hey, sorry for the late response! Once I find some spare time I'll take a look at integrating these, much appreciated!

**Comment by ExtReMLapin** [comment]
New intel, as it's maybe not obvious for position

* Position : two axis position on 2 bytes, first byte is height, second byte is other axis
* Rotation : one axis rotation on 2 bytes
* Scale : on two byte
