### ISSUE TITLE
running on nVidia GeForce Now

### ISSUE THREAD

**Issue by efpresence** [Dealman/Frankensteiner#6]
is it possible to run this on the nvidia geforce now service? only way i can play mordhau...

**Comment by Dealman** [comment]
Don't think so, for all I know I'd probably have to sign some kind of partnership with Nvidia. Not to mention, isn't that platform solely for games?

If there's a way to access the config files of the game via GeForce Now, you probably can at least paste the values in there. But I've never used GeForce Now so I honestly have no clue...
