### ISSUE TITLE
new patchie problems

### ISSUE THREAD

**Issue by zhyph** [Dealman/Frankensteiner#7]
It's been a long time since I used this software, but right now with a new **patchie** and new mercenaries faces to fuck up I felt the need to use this once again, but **as soon as I open it and try to refresh for the mercenaries** to show up, a lot errors appear, and **i'm guessing that is because they changed a deafult loadouts on mercenaries**. Is there any chances for you to look this up?
These 2 screenshots keep iterating until I kill the task in someway. 
Thanks!
![Captura de tela 2021-04-16 111148](https://user-images.githubusercontent.com/68618179/115037273-b09f7f00-9ea4-11eb-8e10-be7a6d9338d4.png)
![Captura de tela 2021-04-16 111202](https://user-images.githubusercontent.com/68618179/115037274-b1381580-9ea4-11eb-8db2-a4cad134cb47.png)

**Comment by Halen84** [comment]
This should be fixed in release 1.3.3.0!

[Reopened issue so others know where to find latest release]
